# Generated by Django 4.0 on 2021-12-07 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 13, 53, 47, 795123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('WIP', 'Wip'), ('ONHOLD', 'Onhold'), ('DONE', 'Done')], default='TODO', max_length=6),
        ),
    ]
